### ISSUE TITLE
Any plan to support Swift 3?

### ISSUE THREAD

**Issue by javiergonzper** [jhays/JHSpinner#6]
Do you plan to update JHSpinner in order to be used on Xcode8 and Swift 3?

Thanks!

**Comment by jhays** [comment]
Yes, I should be able to get it updated soon.

**Comment by javiergonzper** [comment]
Great! Thank you very much!

**Comment by rajat-b** [comment]
> Yes, I should be able to get it updated soon.

waiting..

**Comment by jhays** [comment]
The updates to Swift3 are completed, but I am currently hung up on this CocoaPods issue:

https://github.com/CocoaPods/CocoaPods/pull/5841

**Comment by rajat-b** [comment]
I think this issue is fixed with version 1.1.0.rc.2 as mentioned in the same thread [here](https://github.com/CocoaPods/CocoaPods/pull/5841#issuecomment-246804757)

Even Alamofire [asks](https://github.com/Alamofire/Alamofire#installation) users to use Cocoapods v1.1.0+ for Swift 3 supported installation.

**Comment by jhays** [comment]
Version 0.1.3 with support for Xcode8 / Swift3 is available.
