### ISSUE TITLE
CPU Leak (?)

### ISSUE THREAD

**Issue by caloon** [jhays/JHSpinner#7]
Takes up around 50% of my iPhone 7s CPU. 
I tried removing spinners wherever possible and even setting them to nil. See attached screenshot for details.
![cpu-leak](https://cloud.githubusercontent.com/assets/1286053/20900745/be8a0fde-bb2f-11e6-8629-b8634fd8ce75.png)
Please note: I never called most of these methods which are using up CPU power. I only display a spinner once.

**Comment by jhays** [comment]
Thanks for reporting this. 
At this time, I don't think I will be digging into this issue as JHSpinner falls below a few other priority projects I have on my plate at the moment. 

I am not sure what the cause is, but perhaps the way JHSpinner manipulates constraints as a means of animation is an inefficient solution. Maybe re-writing it to draw the animation manually with CoreGraphics would be more efficient.

**Comment by omaralbeik** [comment]
@caloon I used it in my latest project, the app was consuming power in a crazy way, I was debugging for days then after I got some insights from instruments, it turned out that this was the problem!

@jhays Thank you, you've done a great job with the design of this spinner, I hope you could have time to fix the leak soon ...

**Comment by ggdiez** [comment]
I'm also having the same problem since I'm using Xcode 8.3 and in iOS 10 devices.

**Comment by jhays** [comment]
This issue should be resolved. Thanks for the report.
